/**
 * sails-py generator.
 *
 * @description :: A model definition represents a database table/collection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 *This model has been generated by sails-generator | py

 */

module.exports = {

  attributes: {

  },
  datastore : 'ukwelys_data'

};